(() => {
  const $=s=>document.querySelector(s);let current=null;
  const fmt=t=>new Date(t).toLocaleString('vi-VN',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});
  const renderMsgs=list=>{$('#messages').innerHTML='';for(const m of list){const b=document.createElement('div');b.className='bubble '+m.sender;b.textContent=m.text||'';if(m.image_url){const im=document.createElement('img');im.src=m.image_url;im.alt='Ảnh đính kèm';b.appendChild(im)}const tm=document.createElement('div');tm.className='time';tm.textContent=fmt(m.created_at);b.appendChild(tm);$('#messages').appendChild(b)}$('#messages').scrollTop=$('#messages').scrollHeight};
  async function status(){const r=await fetch('/api/admin/status');return (await r.json()).authenticated}
  async function list(){const r=await fetch('/api/admin/conversations');if(r.status===401){location.reload();return}const d=await r.json();const el=$('#list');el.innerHTML='';for(const c of d.conversations||[]){const item=document.createElement('div');item.className='conv'+(c.id===current?' active':'');item.onclick=()=>open(c.id);item.innerHTML='<span class="conv-name"></span><span class="conv-time"></span>'+(c.admin_unread?'<span class="new-pill"></span>':'');item.querySelector('.conv-name').textContent=c.customer_name||'Khách hàng';item.querySelector('.conv-time').textContent=fmt(c.updated_at);el.appendChild(item)}}
  async function open(id){current=id;const r=await fetch('/api/admin/conversation?id='+encodeURIComponent(id));const d=await r.json();if(!r.ok)return;$('#chatName').textContent=d.conversation.customer_name||'Khách hàng';$('#chatStatus').textContent='Đang hỗ trợ · Cập nhật '+fmt(d.conversation.updated_at);renderMsgs(d.messages||[]);await list()}
  $('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginError').textContent='';const r=await fetch('/api/admin/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password:$('#password').value})});const d=await r.json();if(!r.ok){$('#loginError').textContent=d.error||'Đăng nhập thất bại.';return}$('#login').hidden=true;$('#app').hidden=false;await list();setInterval(list,2500)};
  $('#logout').onclick=async()=>{await fetch('/api/admin/logout',{method:'POST'});location.reload()};
  $('#attach').onclick=()=>$('#file').click();
  $('#composer').onsubmit=async e=>{e.preventDefault();if(!current)return;const f=$('#file').files[0],t=$('#text').value.trim();if(!t&&!f)return;const fd=new FormData();fd.append('conversationId',current);fd.append('text',t);if(f)fd.append('image',f);const btn=e.submitter;btn.disabled=true;try{const r=await fetch('/api/admin/send',{method:'POST',body:fd});const d=await r.json();if(!r.ok)throw Error(d.error||'Lỗi');renderMsgs(d.messages||[]);$('#text').value='';$('#file').value='';await list()}catch(err){alert(err.message)}finally{btn.disabled=false}};
  status().then(ok=>{if(ok){$('#login').hidden=true;$('#app').hidden=false;list();setInterval(list,2500)}});
})();
