name = "auto-bill-support"
compatibility_date = "2026-10-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "auto-bill-chat"
database_id = "0a8cd8b6-6768-4304-aff3-9cfe0bb446e2"
